apiVersion: apps/v1
kind: Deployment

metadata: 
  name: myapp-pod-2
  labels: 
    app: myapp
    type: front-end

spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels: 
        app: myapp
        type: front-end
    spec: 
      containers: 
      - name: nginx-controller
        image: nginx
          