{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ingress-example.serviceAccountName" . }}
  labels:
{{ include "ingress-example.labels" . | nindent 4 }}
{{- end -}}
